services:
  app:
    build: .
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - $MYSQL_DB_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
